server:
  port: 9998
security:
  user:
    name: admin
    password: root
management:
  security:
    enabled: false

spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: monitor-service

eureka:
  instance:
    metadata-map:
      user.name: admin
      user.password: root

logging:
  file: "logs/admin-service-pro.log"