#logging:
#  level:
#    org.springframework.security: INFO

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
#endpoints:
#  health:
#    sensitive: false
#    enabled: true
#  actuator:
#    enabled: true
#    sensitive: false
#  beans:
#    sensitive: false
#    enabled: true


management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true


