server:
  port: 8764


spring:
  zipkin:
    base-url: http://localhost:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
mybatis:
  mapper-locations: classpath:mapping/*.xml
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.winter.model  # 注意：对应实体类的路径