# remote git
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://git.coding.net/xiaoantimes/xiaoantimes-taichi
#          searchPaths: backend/repo
#          username: 124746406@qq.com
#          password:
#      label: master

# ---native
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: config-server

# port
server:
  port: 8769

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
